/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;

/**
 *
 * @author jonat
 */
public class Login_VIEW extends javax.swing.JFrame {

    private JLabel fondoGif;
    private JLayeredPane layeredPane;

    public Login_VIEW() {
        initComponents();
        configurarFondoAnimado();
        personalizarEstilo();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblFoto = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jPswContrasenia = new javax.swing.JPasswordField();
        jBtnIngresar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jLblIcon = new javax.swing.JLabel();
        jLblFondo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLblCrear = new javax.swing.JLabel();
        jBtnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblFoto.setText("Foto User");

        jBtnIngresar.setText("Ingresar");
        jBtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresarActionPerformed(evt);
            }
        });

        jbtnSalir.setText("Cerrar");

        jLblIcon.setText("  ");

        jLblFondo.setText("Fondo");

        lblUsuario.setText("User");

        lblContrasenia.setText("Password");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Bienvenido a la Agenda");

        jLblCrear.setText("¿No tiene suna cuenta? Cree una");

        jBtnCrear.setText("Crear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLblCrear)
                .addGap(71, 71, 71)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLblFondo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsuario)
                                    .addComponent(lblContrasenia))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtUsuario)
                                    .addComponent(jPswContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jBtnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jlblFoto)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblFondo)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLblIcon)
                .addGap(35, 35, 35)
                .addComponent(jlblFoto)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPswContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenia))
                .addGap(49, 49, 49)
                .addComponent(jBtnIngresar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLblCrear)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnCrear)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void personalizarEstilo() {
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24));
        jLabel1.setForeground(new Color(102, 102, 255));
        jLabel1.setText("BIENVENIDO A LA AGENDA");

        jlblFoto.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        jlblFoto.setText("Foto User");
        jlblFoto.setForeground(Color.WHITE);

        lblUsuario.setText("User");
        lblUsuario.setForeground(Color.WHITE);
        lblUsuario.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        lblContrasenia.setText("Password");
        lblContrasenia.setForeground(Color.WHITE);
        lblContrasenia.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        jLblCrear.setText("¿No tiene una cuenta? Cree una");
        jLblCrear.setForeground(Color.WHITE);

        jBtnIngresar.setText("Ingresar");
        jBtnIngresar.setBackground(new Color(0, 123, 255));
        jBtnIngresar.setForeground(Color.WHITE);
        jBtnIngresar.setFocusPainted(false);

        jBtnCrear.setText("Crear");
        jBtnCrear.setBackground(new Color(40, 167, 69));
        jBtnCrear.setForeground(Color.WHITE);
        jBtnCrear.setFocusPainted(false);

        jbtnSalir.setText("Cerrar");
        jbtnSalir.setBackground(new Color(220, 53, 69));
        jbtnSalir.setForeground(Color.WHITE);
        jbtnSalir.setFocusPainted(false);

        ImageIcon icon = new ImageIcon(getClass().getResource("/IMG/user_logo.png"));
        Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        jLblIcon.setIcon(new ImageIcon(img));
    }

    public String getUsername() {
        return jTxtUsuario.getText().trim();
    }

    public String getPassword() {
        return new String(jPswContrasenia.getPassword()).trim();
    }

    private void configurarFondoAnimado() {
        layeredPane = new JLayeredPane();
        layeredPane.setBounds(0, 0, 600, 500);

        fondoGif = new JLabel(new ImageIcon(getClass().getResource("/IMG/giphy.gif")));
        fondoGif.setBounds(0, 0, 600, 500);
        layeredPane.add(fondoGif, Integer.valueOf(0));

        jLabel1.setBounds(140, 10, 400, 40);
        jLblIcon.setBounds(250, 50, 100, 100);
        jlblFoto.setBounds(260, 140, 100, 20);
        lblUsuario.setBounds(170, 180, 70, 25);
        jTxtUsuario.setBounds(250, 180, 120, 25);
        lblContrasenia.setBounds(170, 220, 80, 25);
        jPswContrasenia.setBounds(250, 220, 120, 25);
        jBtnIngresar.setBounds(250, 260, 120, 30);
        jLblCrear.setBounds(180, 300, 250, 20);
        jBtnCrear.setBounds(250, 330, 120, 30);
        jbtnSalir.setBounds(250, 370, 120, 30);

        layeredPane.add(jLabel1, Integer.valueOf(1));
        layeredPane.add(jLblIcon, Integer.valueOf(1));
        layeredPane.add(jlblFoto, Integer.valueOf(1));
        layeredPane.add(lblUsuario, Integer.valueOf(1));
        layeredPane.add(jTxtUsuario, Integer.valueOf(1));
        layeredPane.add(lblContrasenia, Integer.valueOf(1));
        layeredPane.add(jPswContrasenia, Integer.valueOf(1));
        layeredPane.add(jBtnIngresar, Integer.valueOf(1));
        layeredPane.add(jLblCrear, Integer.valueOf(1));
        layeredPane.add(jBtnCrear, Integer.valueOf(1));
        layeredPane.add(jbtnSalir, Integer.valueOf(1));

        setContentPane(layeredPane);
        setSize(600, 500);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_VIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnCrear;
    public javax.swing.JButton jBtnIngresar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLblCrear;
    public javax.swing.JLabel jLblFondo;
    public javax.swing.JLabel jLblIcon;
    public javax.swing.JPasswordField jPswContrasenia;
    public javax.swing.JTextField jTxtUsuario;
    public javax.swing.JButton jbtnSalir;
    public javax.swing.JLabel jlblFoto;
    public javax.swing.JLabel lblContrasenia;
    public javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
